In [1]:
import numpy as np
import pandas as pd
import requests
import matplotlib.pyplot as plt
import csv
import datetime
from bs4 import BeautifulSoup
now = datetime.datetime.now()
%matplotlib inline

In [2]:
name = "/Users/Kyle_Staples/Documents/GitHub/IS834/DataScrape/{}.csv"
data1 = pd.read_csv(name.format("03-05-2019_out"))
data2 = pd.read_csv(name.format("All_Data"))

In [3]:
data1["Player"] = data1["Player"].str.replace('\r','')
data1["Player"] = data1["Player"].str.replace('\n','')

## Make data into final form and merge data

In [4]:
data_final = data1.copy()
data_final.update(data2)
data_final = pd.concat([data1,data2], keys = "Player")
data_final = data_final.sort_values(["Date","Games"], ascending = False ).drop_duplicates(subset = "Player", keep="first", inplace = False)

/anaconda3/envs/Python_37/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until

## Export data into final

In [5]:
data_final = data_final.sort_values("MMR", ascending = False )
path = '/Users/Kyle_Staples/Documents/GitHub/IS834/DataScrape/All_Data.csv'
data_final.to_csv(path, sep=',', index = False, encoding='utf-8')

# Extra Test code to be run later

In [287]:
data_final = data_final.sort_values("MMR", ascending = False )

                  Date  Games      MMR          Player      Rank  Unnamed: 0
l 198479  3/4/19 13:24    360 -2627.63        MrPJSalt  169932.0        32.0
  198480  3/4/19 13:24    218 -2942.56  copper4arrived  169933.0        33.0
  198481  3/4/19 13:24    267 -3005.59      youdiedlol  169934.0        34.0
  198482  3/4/19 13:24    359 -3363.59   ViggoTarasov1  169935.0        35.0
  198483  3/4/19 13:24    574 -3564.89           Diouz  169936.0        36.0

In [10]:
data_final.loc[data_final.Player == data_final.Player].tail()

                  Date  Games      MMR          Player      Rank  Unnamed: 0
l 198479  3/4/19 13:24    360 -2627.63        MrPJSalt  169932.0        32.0
  198480  3/4/19 13:24    218 -2942.56  copper4arrived  169933.0        33.0
  198481  3/4/19 13:24    267 -3005.59      youdiedlol  169934.0        34.0
  198482  3/4/19 13:24    359 -3363.59   ViggoTarasov1  169935.0        35.0
  198483  3/4/19 13:24    574 -3564.89           Diouz  169936.0        36.0

In [18]:
data_final.loc[data_final.duplicated() == True]

Empty DataFrame
Columns: [Date, Games, MMR, Player, Rank, Unnamed: 0]
Index: []

In [13]:
data2.loc[data2["MMR"] <= 1400]

                 Date  Games      MMR           Player      Rank  Unnamed: 0
190415   3/4/19 13:24    265  1400.00       Inferno.x2  163287.0        87.0
190416   3/4/19 13:24    149  1399.99    Z0DIAC_KILLER  163288.0        88.0
190417   3/4/19 13:24     12  1399.99      ComfyJaguar  163289.0        89.0
190418   3/4/19 13:24     33  1399.91   alphanoob.noob  163290.0        90.0
190419   3/4/19 13:24     28  1399.90      SWAAwilliam  163292.0        92.0
190420   3/4/19 13:24    111  1399.90    Abdus-Salam67  163291.0        91.0
190421   3/4/19 13:24    317  1399.88            JenZG  163293.0        93.0
190422   3/4/19 13:24    155  1399.71  WHITE_WOLF_ENVY  163295.0        95.0
190423   3/4/19 13:24     66  1399.67      Motion.Less  163296.0        96.0
190424  2/28/19 14:13     63  1399.57    MrBackfischLP       NaN         NaN
190425  2/28/19 14:13    127  1399.57  EhrenbruderNoah       NaN         NaN
190426   3/4/19 13:24     42  1399.40        SoBReTeeR  163297.0        97.0
190427   3/4/19 13:24     61  1399.39          OSHIINN  163298.0        98.0
190428   3/4/19 13:24     14  1399.36   thesweettalker  163299.0        99.0
190429   3/4/19 13:24     51  1399.36           yT.BoB  163300.0       100.0
190430   3/4/19 13:24     18  1399.31    YaBoyLumbeeYT  163301.0         1.0
190431   3/4/19 13:24     74  1399.28        r6.chanka  163302.0         2.0
190432   3/4/19 13:24    215  1399.27       SirSanty.-  163303.0         3.0
190433   3/4/19 13:24     39  1399.27        frolikeye  163304.0         4.0
190434   3/4/19 13:24     60  1399.19    MontagneTiger  163305.0         5.0
190435  2/28/19 14:13    271  1399.06       serpongeMG       NaN         NaN
190436  2/28/19 14:13    734  1398.88          Squegie       NaN         NaN
190437   3/4/19 13:24    454  1398.84      sour.sweets  163306.0         6.0
190438   3/4/19 13:24    133  1398.72  RFW_Nickelkette  163307.0         7.0
190439   3/4/19 13:24     89  1398.65        PEPE-9001  163308.0         8.0
190440   3/4/19 13:24      9  1398.54       UncleHonor  163310.0        10.0
190441   3/4/19 13:24     80  1398.54           Diosa.  163309.0         9.0
190442  2/28/19 14:13     20  1398.42     Raw_Rae_TriX       NaN         NaN
190443   3/4/19 13:24    314  1398.41     Buxtonsniper  163311.0        11.0
190444   3/4/19 13:24     42  1398.41  MigosTakeOffYRN  163312.0        12.0
...               ...    ...      ...              ...       ...         ...
198454   3/4/19 13:24    262  -989.37          Sen.to.  169905.0         5.0
198455   3/4/19 13:24    224 -1023.58         TheLaw_.  169906.0         6.0
198456   3/4/19 13:24    214 -1042.34     ImNotGoodBTW  169907.0         7.0
198457   3/4/19 13:24    148 -1046.62       Mr.Friend.  169908.0         8.0
198458   3/4/19 13:24    176 -1138.36   Pokemonster929  169909.0         9.0
198459   3/4/19 13:24    154 -1156.03             JyCS  169910.0        10.0
198460   3/4/19 13:24   2062 -1159.40  Danny.Delicious  169911.0        11.0
198461   3/4/19 13:24    398 -1314.17     Stone_Ranger  169912.0        12.0
198462   3/4/19 13:24    167 -1318.64       Piggo_Boar  169913.0        13.0
198463   3/4/19 13:24    257 -1374.42     ElkkuZombie-  169914.0        14.0
198464   3/4/19 13:24    252 -1389.18     Generlc.Name  169915.0        15.0
198465   3/4/19 13:24    459 -1403.70  PrcsLeiaDyedLOL  169916.0        16.0
198466   3/4/19 13:24    352 -1420.75           TaqiiG  169917.0        17.0
198467   3/4/19 13:24     82 -1441.15  reddit_buzzword  169919.0        19.0
198468   3/4/19 13:24    125 -1458.66     GoldenChamp.  169920.0        20.0
198469   3/4/19 13:24    171 -1463.46  Mother.Russia..  169921.0        21.0
198470   3/4/19 13:24    743 -1492.08  YameteOnii-chan  169922.0        22.0
198471   3/4/19 13:24     83 -1539.65      ImDeranking  169924.0        24.0
198472   3/4/19 13:24    125 -1720.09   FuzeWasHere.eF  169925.0        25.0
198473   3/4/19 13:24    381 -1864.93  InjureTeammates  169926.0        26.0
198474   3/4/19 13:24    390 -1966.04  ToK1XKMongoIoid  169927.0        27.0
198475   3/4/19 13:24    154 -2076.58   SubPewDiePie88  169928.0        28.0
198476   3/4/19 13:24    155 -2505.30     thehumantaco  169929.0        29.0
198477   3/4/19 13:24    119 -2545.25     RektByUnRank  169930.0        30.0
198478   3/4/19 13:24    241 -2606.88        luvz2spwg  169931.0        31.0
198479   3/4/19 13:24    360 -2627.63         MrPJSalt  169932.0        32.0
198480   3/4/19 13:24    218 -2942.56   copper4arrived  169933.0        33.0
198481   3/4/19 13:24    267 -3005.59       youdiedlol  169934.0        34.0
198482   3/4/19 13:24    359 -3363.59    ViggoTarasov1  169935.0        35.0
198483   3/4/19 13:24    574 -3564.89            Diouz  169936.0        36.0

[8069 rows x 6 columns]